[tools]
bat = "latest"
btop = "latest"
bun = "latest"
delta = "latest"
direnv = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
go = "latest"
jq = "latest"
lazygit = "latest"
neovim = "latest"
node = "lts"
opencode = "latest"
"npm:agent-browser" = { version = "latest", depends = ["node"] }
"npm:@mariozechner/pi-coding-agent" = { version = "latest", depends = ["node"] }
pnpm = "latest"
python = "latest"
ripgrep = "latest"
starship = "latest"
uv = "latest"
zoxide = "latest"
